# Generated by Django 4.0.6 on 2022-07-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='add_by',
        ),
    ]
